version: '3.7'
networks:
  network_1:
    driver: bridge
services:
  ca_bsestest:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bsestest.dataauth.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - '11054:11054'
    command: 'sh -c ''fabric-ca-server start -b admin:adminpw -d'''
    volumes:
      - '/home/bishesh/DA/blockchain/artifacts/channel/create-certificates-with-ca/fabric-ca/bsestest:/etc/hyperledger/fabric-ca-server'
    hostname: ca.bsestest.dataauth.com
    container_name: ca.bsestest.dataauth.com
    networks:
      - network_1
